apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app-deployment
  labels:
      app: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: local/app
        imagePullPolicy: Never
        ports:
        - name: app-service
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  selector:
    app: app
  ports:
  - port: 8080
    targetPort: app-service
